### ISSUE TITLE
Problems with wfm-file from a DS1054Z

### ISSUE THREAD

**Issue by Phi1983** [scottprahl/RigolWFM#18]
Hi,
I've got a problem when using your software for wfm-files saved with a Rigol DS1054Z. I've recorded 2 channels: 1 and 2. When I have a look at the data in python or using the wfmconvert, the voltage-values are swapped between channel 1 and 2. However, the voltage scale and probe values (e.g. 10X) are not, so that not only the signal curves are swapped between channel 1 and 2 but also wrong scaled. 

The firmware is 00.04.04.SP3

Best
Philipp

**Comment by scottprahl** [comment]
are you using the latest released version?  If so then upload a scope screenshot and the .wfm file and I will try to figure out what is going on.

**Comment by Phi1983** [comment]
Ups, sorry. I've installed it 2 weeks ago and didn't realize that there is a new version ... now upgraded it and the problem is gone ...

Sorry again and thanks for your fast reply.
