### ISSUE TITLE
invalid syntax with wfmconvert

### ISSUE THREAD

**Issue by goodjing50** [scottprahl/RigolWFM#20]
Hello, I want to use wfmconvert to convert .wfm to .csv.
The follows are my codes, and then I meet error.

## Code 1
`import RigolWFM.wfm as rigol
import RigolWFM.wfmconvert

filename = 'Newfile1.wfm'
scope = 'DS2072A'

w = rigol.Wfm.from_file(filename, scope)
RigolWFM.wfmconvert 2 csv Newfile1.wfm`

## Error Message 1
  File "/Users/Ronja/Desktop/scopedata/wfmdata.py", line 9
    RigolWFM.wfmconvert 2 csv Newfile1.wfm
                        ^
SyntaxError: invalid syntax

## Code 2
`import RigolWFM.wfm as rigol
import RigolWFM.wfmconvert

filename = 'Newfile1.wfm'
scope = 'DS2072A'

w = rigol.Wfm.from_file(filename, scope)
RigolWFM.wfmconvert.csv(2,'Newfile1.wfm','convertfile')`

## Error Message 2
 /usr/local/bin/python3 /Users/Ronja/Desktop/scopedata/wfmdata.py
Traceback (most recent call last):
  File "/Users/Ronja/Desktop/scopedata/wfmdata.py", line 9, in <module>
    RigolWFM.wfmconvert.csv(2,'Newfile1.wfm','convertfile')
  File "/Users/Ronja/Library/Python/3.9/lib/python/site-packages/RigolWFM/wfmconvert.py", line 40, in csv
    s = scope_data.csv()
AttributeError: 'str' object has no attribute 'csv'

Thank you for your help!

**Comment by scottprahl** [comment]
Hmm. If you just want to convert the .wfm file, then just use the command line

```bash
wfmconvert.py 2 csv  'Newfile1.wfm'
```

If you need to do this in a python script then do something like
```python
import RigolWFM.wfm as rigol

filename = 'wfm/DS2072A-1.wfm'
scope = 'DS2072A'

scope_data = rigol.Wfm.from_file(filename, scope)

description = scope_data.describe()
print(description)

s = scope_data.csv()

# just show the first few entries
rows = s.split('\n')
for i in range(5):
    print(rows[i])
```

**Comment by goodjing50** [comment]
> Hmm. If you just want to convert the .wfm file, then just use the command line
> 
> ```shell
> wfmconvert.py 2 csv  'Newfile1.wfm'
> ```
> 
> If you need to do this in a python script then do something like
> 
> ```python
> import RigolWFM.wfm as rigol
> 
> filename = 'wfm/DS2072A-1.wfm'
> scope = 'DS2072A'
> 
> scope_data = rigol.Wfm.from_file(filename, scope)
> 
> description = scope_data.describe()
> print(description)
> 
> s = scope_data.csv()
> 
> # just show the first few entries
> rows = s.split('\n')
> for i in range(5):
>     print(rows[i])
> ```

Thank you very much for the reply. I made it run successfully.
